name: ci

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  check:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.9"]
    container: python:${{ matrix.python-version }}-bullseye
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install python dependencies
        run: make devdeps
      - name: Create dotenv file
        run: cp .env.sample .env
      - name: Check source code issues
        run: make check
  test:
    needs: check
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.8", "3.9", "3.10"]
    container: python:${{ matrix.python-version }}-bullseye
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install python dependencies
        run: make devdeps
      - name: Create dotenv file
        run: cp .env.sample .env
      - name: Run tests
        run: make test
